name: Tests

on:
  pull_request:
  workflow_call:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: default

      - name: Run pytest
        run: pixi run test
